# Generated by Django 4.0.3 on 2023-06-14 15:49

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='RoomBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=300)),
                ('meeting_title', models.CharField(max_length=300)),
                ('date', models.DateField()),
                ('start_time', models.TimeField(validators=[django.core.validators.MinValueValidator(datetime.time(9, 0)), django.core.validators.MaxValueValidator(datetime.time(18, 0))])),
                ('end_time', models.TimeField(validators=[django.core.validators.MinValueValidator(datetime.time(9, 0)), django.core.validators.MaxValueValidator(datetime.time(18, 0))])),
                ('room_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.room')),
            ],
        ),
    ]
