# Generated by Django 4.0.3 on 2023-06-08 10:55

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=300)),
                ('meeting_title', models.CharField(max_length=300)),
                ('date', models.DateField()),
                ('room_number', models.CharField(choices=[('Room 1', 'room 1'), ('Room 2', 'room 2')], max_length=100)),
                ('start_time', models.TimeField(validators=[django.core.validators.MinValueValidator(datetime.time(9, 0)), django.core.validators.MaxValueValidator(datetime.time(18, 0))])),
                ('end_time', models.TimeField(validators=[django.core.validators.MinValueValidator(datetime.time(9, 0)), django.core.validators.MaxValueValidator(datetime.time(18, 0))])),
            ],
        ),
    ]
