# Generated by Django 4.0.3 on 2023-06-07 12:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RommBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=300)),
                ('meeting_title', models.CharField(max_length=300)),
                ('start_time', models.TimeField(validators=[django.core.validators.MinValueValidator('09:00'), django.core.validators.MaxValueValidator('18:00')])),
                ('end_time', models.TimeField(validators=[django.core.validators.MinValueValidator('09:00'), django.core.validators.MaxValueValidator('18:00')])),
            ],
        ),
    ]
