# Generated by Django 4.2.2 on 2023-06-15 15:02

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roombooking',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='roombooking',
            name='end_time',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.time(9, 0)), django.core.validators.MaxValueValidator(datetime.time(18, 0))]),
        ),
        migrations.AlterField(
            model_name='roombooking',
            name='start_time',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.time(9, 0)), django.core.validators.MaxValueValidator(datetime.time(18, 0))]),
        ),
    ]
