# Generated by Django 4.0.3 on 2023-06-07 12:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=300)),
                ('meeting_title', models.CharField(max_length=300)),
                ('date', models.DateField(auto_now=True)),
                ('start_time', models.TimeField(validators=[django.core.validators.MinValueValidator('09:00'), django.core.validators.MaxValueValidator('18:00')])),
                ('end_time', models.TimeField(validators=[django.core.validators.MinValueValidator('09:00'), django.core.validators.MaxValueValidator('18:00')])),
            ],
        ),
        migrations.DeleteModel(
            name='RommBooking',
        ),
    ]
