# Generated by Django 4.0.3 on 2023-06-14 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roombooking',
            name='room_name',
            field=models.ForeignKey(default='Romm 1', on_delete=django.db.models.deletion.CASCADE, to='room.room'),
        ),
    ]
