# Generated by Django 4.0.3 on 2023-06-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_roombooking_delete_rommbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='roombooking',
            name='room_number',
            field=models.CharField(choices=[('room1', 'Room 1'), ('room2', 'Room 2')], default=None, max_length=10),
        ),
    ]
