# Generated by Django 4.0.3 on 2023-06-16 09:05

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_alter_roombooking_date_alter_roombooking_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roombooking',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='roombooking',
            name='end_time',
            field=models.TimeField(validators=[django.core.validators.MinValueValidator(datetime.time(9, 0)), django.core.validators.MaxValueValidator(datetime.time(18, 0))]),
        ),
        migrations.AlterField(
            model_name='roombooking',
            name='start_time',
            field=models.TimeField(validators=[django.core.validators.MinValueValidator(datetime.time(9, 0)), django.core.validators.MaxValueValidator(datetime.time(18, 0))]),
        ),
        migrations.AddConstraint(
            model_name='roombooking',
            constraint=models.CheckConstraint(check=models.Q(('room_name__isnull', False), ('date__isnull', False), ('start_time__lt', django.db.models.expressions.F('end_time'))), name='check_room_booking'),
        ),
    ]
