# Generated by Django 4.0.3 on 2023-06-16 16:30

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_remove_roombooking_check_room_booking'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='roombooking',
            constraint=models.CheckConstraint(check=models.Q(('room_name__isnull', False), ('date__isnull', False), ('start_time__lt', django.db.models.expressions.F('end_time')), ('end_time__gt', django.db.models.expressions.F('start_time'))), name='check_room_booking'),
        ),
    ]
