# Generated by Django 4.0.3 on 2023-06-13 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_roombooking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roombooking',
            old_name='room',
            new_name='room_name',
        ),
    ]
