# Generated by Django 4.0.3 on 2023-06-07 15:26

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_alter_roombooking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roombooking',
            name='end_time',
            field=models.TimeField(validators=[django.core.validators.MinValueValidator(datetime.time(9, 0)), django.core.validators.MaxValueValidator(datetime.time(18, 0))]),
        ),
        migrations.AlterField(
            model_name='roombooking',
            name='start_time',
            field=models.TimeField(validators=[django.core.validators.MinValueValidator(datetime.time(9, 0)), django.core.validators.MaxValueValidator(datetime.time(18, 0))]),
        ),
    ]
